export const EMOJIS = [
    { name: 'Laughing', emoji: '😂' },
    { name: 'Heart Eyes', emoji: '😍' },
    { name: 'Winking Face', emoji: '😉' },
    { name: 'Tears of Joy', emoji: '😅' },
    { name: 'Smirking', emoji: '😏' },
    { name: 'Blushing', emoji: '😊' },
    { name: 'Thumbs Up', emoji: '👍' },
    { name: 'Clapping', emoji: '👏' },
    { name: 'OK Hand', emoji: '👌' },
    { name: 'Wave', emoji: '👋' },
    { name: 'Party Popper', emoji: '🎉' },
    { name: 'Confetti Ball', emoji: '🎊' },
    { name: 'Sparkles', emoji: '✨' },
    { name: 'Fire', emoji: '🔥' },
    { name: 'Rocket', emoji: '🚀' },
    { name: 'Sunglasses', emoji: '😎' },
    { name: 'Thinking', emoji: '🤔' },
    { name: 'Sunny', emoji: '☀️' },
    { name: 'Cloudy', emoji: '☁️' },
    { name: 'Rainy', emoji: '🌧️' },
    { name: 'Thunderstorm', emoji: '⛈️' },
    { name: 'Snowy', emoji: '❄️' },
    { name: 'Windy', emoji: '🌬️' },
    { name: 'Foggy', emoji: '🌫️' },
    { name: 'Umbrella', emoji: '☂️' },
    { name: 'Tornado', emoji: '🌪️' },
    { name: 'Rainbow', emoji: '🌈' }
  ];